# configs/small_vs_large_magnitude/source_loreta_p1_small_vs_large_magnitude.yaml

# 1. Metadata
analysis_name: "source_loreta_p1_small_vs_large_magnitude"
domain: "source"

# 2. Epoch Time Window and Baseline Correction
epoch_window:
  tmin: -0.2
  tmax: 0.496
  baseline: [-0.2, 0.0]

# 3. Contrast Definition
# Tests: "N1 amplitudes varied across the 1~6 range, with stronger modulation in the 1~3 range"
# Tests dual-stage model: Parallel individuation (1-3) vs. Estimation (4-6)
contrast:
  name: "Small (1-3) vs. Large (4-6) Magnitude"
  condition_A:
    name: "Small Magnitude"
    condition_set_name: "ALL_SMALL_TRANSITIONS"
  condition_B:
    name: "Large Magnitude"
    condition_set_name: "ALL_LARGE_TRANSITIONS"
  combination_weights: [1, -1]

# 4. Source Reconstruction Parameters
source:
  method: "eLORETA"
  snr: 2.0

# --- Inverse Solution Parameters ---
inverse:
  loose: 0.2
  depth: 3.0

# 5. Statistical Analysis Parameters
stats:
  analysis_window: [0.060, 0.140]
  p_threshold: 0.15
  cluster_alpha: 0.05
  n_permutations: 10000
  tail: 0 # two-sided test
  seed: 42 # for reproducibility
  method: threshold
  tfce:
    start: 0.0
    step: 0.2
  n_jobs: -1
  buffer_size: 1000
  roi:
    parc: aparc
    labels:
      # Early visual P1 generators
      - pericalcarine
      - cuneus
      - lingual
      - lateraloccipital
      - fusiform
