# configs/13_31_hs/source_loreta_hs_13_31_n1.yaml
# Hyde & Spelke style localization for the 1↔3 contrast during the N1 window.

analysis_name: "source_loreta_hs_100-300_13_31"
domain: "source"

epoch_window:
  tmin: -0.2
  tmax: 0.496
  baseline: [-0.2, 0.0]

contrast:
  name: "1↔3 Transition: Increasing vs. Decreasing"
  condition_A:
    name: "1 to 3 (Increasing)"
    condition_set_name: "TRANSITION_13"
  condition_B:
    name: "3 to 1 (Decreasing)"
    condition_set_name: "TRANSITION_31"
  combination_weights: [1, -1]

source:
  method: "eLORETA"
  snr: 2.0
  pick_ori: normal

inverse:
  loose: 0.2
  depth: 3.0
  source_spacing: ico-4

postprocess:
  normalize_log_total_current: true
  normalization_power: 1.0

stats:
  analysis_window: [0.100, 0.300]
  p_threshold: 0.05
  cluster_alpha: 0.05
  n_permutations: 10000
  tail: 0
  seed: 42
  method: threshold
  n_jobs: -1
  buffer_size: 1000

  vertex:
    enabled: true
    restrict_to_roi: false

  label_timeseries:
    enabled: false

