# configs/Acc0_vs_Acc1/source_loreta_p1_Acc0_vs_Acc1.yaml

analysis_name: "source_loreta_p1_Acc0_vs_Acc1"
domain: "source"

epoch_window:
  tmin: -0.2
  tmax: 0.496
  baseline: [-0.2, 0.0]

contrast:
  name: "All Conditions: Acc0 vs Acc1"
  condition_A:
    name: "AllConditions-Acc0"
    condition_set_name: "ALL_NUMEROSITY_TRANSITIONS"
    accuracy: "acc0"
  condition_B:
    name: "AllConditions-Acc1"
    condition_set_name: "ALL_NUMEROSITY_TRANSITIONS"
    accuracy: "acc1"
  combination_weights: [1, -1]

source:
  method: "eLORETA"
  snr: 2.0

inverse:
  loose: 0.2
  depth: 3.0

stats:
  analysis_window: [0.080, 0.140]
  p_threshold: 0.15
  cluster_alpha: 0.05
  n_permutations: 10000
  tail: 0
  seed: 42
  method: threshold
  tfce:
    start: 0.0
    step: 0.2
  n_jobs: -1
  buffer_size: 1000
  roi:
    parc: aparc
    labels:
      - lateraloccipital
      - fusiform
      - pericalcarine
      - cuneus
      - lingual


