# configs/sensor_small_to_small_direction.yaml

# 1. Metadata
analysis_name: "sensor_small_to_small_direction"
domain: "sensor"

# 2. Epoch Time Window and Baseline Correction
epoch_window:
  tmin: -0.2
  tmax: 0.496
  baseline: [-0.2, 0.0]

# 3. Contrast Definition
# Tests: "Decreasing Small-to-Small transitions elicited especially shallow N1 amplitudes"
# This is your STRONGEST effect from the abstract
contrast:
  name: "Small-to-Small: Increasing vs. Decreasing"
  condition_A:
    name: "Small Increasing"
    condition_set_name: "SMALL_TO_SMALL_INCREASING"
  condition_B:
    name: "Small Decreasing"
    condition_set_name: "SMALL_TO_SMALL_DECREASING"
  combination_weights: [1, -1]

# 4. Statistical Analysis Parameters
stats:
  analysis_window: [0.00, 0.496]
  p_threshold: 0.005
  cluster_alpha: 0.05
  n_permutations: 5000
  tail: 0  # two-sided test
  seed: 42 # for reproducibility
  connectivity:
    method: "distance"
    threshold: 0.04 # 4 cm
  # --- Optional ROI restriction (sensor space, uncomment to enable) ---
  # Restricts cluster-based permutation testing to specified sensor regions.
  # ROI definitions are centrally managed in configs/sensor_roi_definitions.yaml
  # roi:
  #   channel_groups:
  #     - posterior_visual_parietal  # Combined N1 + P1 + P3b regions
  # Or specify individual regions:
  # roi:
  #   channel_groups:
  #     - N1_bilateral
  #     - P1_Oz
  #     - P3b_midline

# 5. Visualization Parameters
visualizations:
  erp:
    channels: []
  topomap:
    times: []
