# configs/small_to_small_direction/source_dspm_p3b_small_to_small_direction.yaml

# 1. General Analysis Information
analysis_name: "source_dspm_p3b_small_to_small_direction"
domain: "source"

# 2. Epoch Time Window and Baseline Correction
epoch_window:
  tmin: -0.2
  tmax: 0.496
  baseline: [-0.2, 0.0]

# 3. Contrast Definition
# Tests: "Decreasing Small-to-Small transitions elicited especially shallow N1 amplitudes"
# This is your STRONGEST effect from the abstract (P3b window)
contrast:
  name: "Small-to-Small: Increasing vs. Decreasing"
  condition_A:
    name: "Small Increasing"
    condition_set_name: "SMALL_TO_SMALL_INCREASING"
  condition_B:
    name: "Small Decreasing"
    condition_set_name: "SMALL_TO_SMALL_DECREASING"
  combination_weights: [1, -1]

# 4. Source Reconstruction Parameters
source:
  method: "dSPM"
  snr: 2.0

# --- Inverse Solution Parameters ---
# loose: Orientation constraint (0.2 is a good default for EEG)
# depth: Depth weighting. 0.8 is for MEG; ~3.0 is better for EEG.
inverse:
  loose: 0.2
  depth: 3.0

# 5. Statistical Analysis Parameters
stats:
  analysis_window: [0.30, 0.496]
  # p_threshold is ignored when using TFCE; retained here for reference only.
  p_threshold: 0.15
  cluster_alpha: 0.05
  n_permutations: 10000
  tail: 0 # two-sided test
  seed: 42 # for reproducibility
  method: threshold
  tfce:
    start: 0.0
    step: 0.2
  n_jobs: -1
  buffer_size: 1000
  roi:
    parc: aparc
    labels:
      # P3b canonical generators (parietal/cingulate, NOT visual)
      - inferiorparietal      # Inferior parietal lobule (IPL) - CRITICAL
      - superiorparietal      # Superior parietal lobule (SPL) - CRITICAL
      - precuneus             # Medial parietal - CRITICAL
      - supramarginal         # Angular gyrus, TPJ region - IMPORTANT
      - posteriorcingulate    # Posterior cingulate cortex (PCC)
      - isthmuscingulate      # Isthmus of cingulate
      - superiortemporal      # Superior temporal (TPJ, memory network)
