# configs/sensor_cardinality2_vs_cardinality3.yaml

# 1. General Analysis Information
analysis_name: "sensor_cardinality2_vs_cardinality3"
domain: "sensor"

# 2. Epoch Time Window and Baseline Correction
epoch_window:
  tmin: -0.1
  tmax: 0.6
  baseline: [-0.1, 0.0]

# 3. Contrast Definition
contrast:
  name: "Cardinality 2 vs. Cardinality 3"
  condition_A:
    name: "Cardinality 2"
    condition_set_name: "CARDINALITY_2"
  condition_B:
    name: "Cardinality 3"
    condition_set_name: "CARDINALITY_3"
  combination_weights: [1, -1]

# 4. Statistical Analysis Parameters
stats:
  analysis_window: [0.00, 0.6]
  p_threshold: 0.001
  cluster_alpha: 0.01
  n_permutations: 1024
  tail: 1  # two-sided test
  seed: 42 # for reproducibility
  connectivity:
    method: "distance"
    threshold: 0.04 # 4 cm

# 5. Visualization Parameters
visualizations:
  erp:
    channels: []
  topomap:
    times: []

