# configs\change_vs_no-change\sensor_change_vs_no-change.yaml

# 1. Metadata
analysis_name: "sensor_change_vs_no-change"
domain: "sensor"  # 'sensor' or 'source'

# 2. Data Selection
epoch_window:
  tmin: -0.2
  tmax: 0.496
  baseline: [-0.2, 0.0]

# 3. Contrast Definition
# Defines the two groups of conditions to be contrasted.
# The `include` lists should contain condition names that are present
# in the MNE Epochs metadata. The original project's `condition_sets.yaml`
# can be a reference, but the core script will filter based on metadata columns.
contrast:
  name: "Change vs. NoChange"
  condition_A:
    name: "Change"
    condition_set_name: "DIRECTION_CHANGE"
  condition_B:
    name: "NoChange"
    condition_set_name: "CARDINALITY_NO_CHANGE"
  # Parameter from the Jas et al. (2018) paper and the IA's report.
  # Using explicit numeric weights `[1, -1]` is the clearest way to define a subtraction.
  # This avoids ambiguity with trial counts.
  combination_weights: [1, -1]

# 4. Statistical Analysis Parameters
stats:
  analysis_window: [0.00, 0.496]
  p_threshold: 0.01
  cluster_alpha: 0.05
  n_permutations: 5000
  tail: 0  # two-sided test
  seed: 42 # for reproducibility
  connectivity:
    method: "distance"
    threshold: 0.04 # 4 cm

# 5. Visualization Parameters
visualizations:
  erp:
    channels: []
  topomap:
    times: []

