# configs/source_loreta_change_vs_no-change.yaml

# 1. Metadata
analysis_name: "source_loreta_change_vs_no-change"
domain: "source"

# 2. Data Selection (same as sensor space for contrast creation)
epoch_window:
  tmin: -0.1
  tmax: 0.6
  baseline: [-0.1, 0.0]

# 3. Contrast Definition (same as sensor space)
contrast:
  name: "Change vs. NoChange"
  condition_A:
    name: "Change"
    condition_set_name: "DIRECTION_CHANGE"
  condition_B:
    name: "NoChange"
    condition_set_name: "CARDINALITY_NO_CHANGE"
  combination_weights: [1, -1]

# 4. Source Reconstruction Parameters
source:
  method: "eLORETA"
  snr: 3.0

# --- Inverse Solution Parameters ---
# These parameters are used when generating inverse operators.
inverse:
  loose: 0.2
  depth: 3.0

# 5. Cluster Statistics Parameters
stats:
  analysis_window: [0.3, 0.496]
  p_threshold: 0.05
  cluster_alpha: 0.05
  n_permutations: 5000
  tail: 0 # two-sided
