# configs/new_user/templates/source_dspm_n1_TEMPLATE.yaml
#
# SOURCE-SPACE ANALYSIS TEMPLATE (dSPM method, N1 component)
# This file localizes brain sources for N1 effects (~80-200 ms).
#
# WHEN TO USE: After finding significant N1 effects in sensor analysis
# NAMING: Must end with same suffix as sensor file (e.g., sensor_X.yaml → source_dspm_n1_X.yaml)

# 1. Metadata
analysis_name: "source_dspm_n1_TEMPLATE"  # ← CHANGE THIS to match filename
domain: "source"  # Always "source" for brain localization

# 2. Epoch Time Window and Baseline Correction
epoch_window:
  tmin: -0.2
  tmax: 0.496
  baseline: [-0.2, 0.0]

# 3. Contrast Definition (MUST MATCH your sensor file)
contrast:
  name: "Condition A vs. Condition B"
  condition_A:
    name: "Condition A"
    condition_set_name: "CARDINALITY_1"  # ← CHANGE THIS (same as sensor)
  condition_B:
    name: "Condition B"
    condition_set_name: "CARDINALITY_2"  # ← CHANGE THIS (same as sensor)
  combination_weights: [1, -1]

# 4. Source Reconstruction Parameters
source:
  method: "dSPM"   # dSPM method (dynamic Statistical Parametric Mapping)
  snr: 2.0         # Signal-to-noise ratio (keep at 2.0)

inverse:
  loose: 0.2       # Orientation constraint (0.2 = standard)
  depth: 3.0       # Depth weighting (3.0 = appropriate for EEG)

# 5. Statistical Analysis Parameters
stats:
  analysis_window: [0.080, 0.200]  # ← NARROW THIS based on sensor N1 peak (e.g., ±20 ms)
  p_threshold: 0.15       # More liberal for source (fewer data points than sensor)
  cluster_alpha: 0.05
  n_permutations: 10000   # More permutations for stable source results
  tail: 0                 # 0 = two-sided (or match sensor tail)
  seed: 42
  method: threshold       # Clustering method
  tfce:
    start: 0.0
    step: 0.2
  n_jobs: -1              # Use all CPU cores
  buffer_size: 1000

  # ROI Restriction (brain regions for N1)
  roi:
    parc: aparc           # FreeSurfer parcellation
    labels:
      # Visual and parietal N1 generators
      - lateraloccipital
      - fusiform
      - inferiorparietal
      - superiorparietal
      - precuneus
      - pericalcarine
      - cuneus
      - lingual
