# configs/large_to_large_direction/source_loreta_p3b_large_to_large_direction.yaml

# 1. Metadata
analysis_name: "source_loreta_p3b_large_to_large_direction"
domain: "source"

# 2. Epoch Time Window and Baseline Correction
epoch_window:
  tmin: -0.2
  tmax: 0.496
  baseline: [-0.2, 0.0]

# 3. Contrast Definition (same as sensor space)
contrast:
  name: "Large-to-Large: Increasing vs. Decreasing"
  condition_A:
    name: "Large Increasing"
    condition_set_name: "LARGE_TO_LARGE_INCREASING"
  condition_B:
    name: "Large Decreasing"
    condition_set_name: "LARGE_TO_LARGE_DECREASING"
  combination_weights: [1, -1]

# 4. Source Reconstruction Parameters
source:
  method: "eLORETA"
  snr: 2.0

# --- Inverse Solution Parameters ---
inverse:
  loose: 0.2
  depth: 3.0

# 5. Statistical Analysis Parameters
stats:
  analysis_window: [0.30, 0.496]
  p_threshold: 0.15
  cluster_alpha: 0.05
  n_permutations: 10000
  tail: 0 # two-sided test
  seed: 42 # for reproducibility
  method: threshold
  tfce:
    start: 0.0
    step: 0.2
  n_jobs: -1
  buffer_size: 1000
  roi:
    parc: aparc
    labels:
      - inferiorparietal
      - superiorparietal
      - precuneus
      - supramarginal
      - posteriorcingulate
      - isthmuscingulate
      - superiortemporal
