# configs/13_31/source_loreta_100-300_vertex_13_31.yaml

# 1. Metadata
analysis_name: "source_loreta_100-300_vertex_13_31"
domain: "source"

# 2. Epoch Time Window and Baseline Correction
epoch_window:
  tmin: -0.2
  tmax: 0.496
  baseline: [-0.2, 0.0]

# 3. Contrast Definition
# Tests: 100-300ms window - Frontal/ACC focus (sensor Cluster #2)
contrast:
  name: "1<->3 Transition: Increasing vs. Decreasing"
  condition_A:
    name: "1 to 3 (Increasing)"
    condition_set_name: "TRANSITION_13"
  condition_B:
    name: "3 to 1 (Decreasing)"
    condition_set_name: "TRANSITION_31"
  combination_weights: [1, -1]

# 4. Source Reconstruction Parameters
source:
  method: "eLORETA"
  snr: 2.0
  pick_ori: vector  # Orientation-invariant magnitude for group stats

# --- Inverse Solution Parameters ---
inverse:
  loose: 0.2
  depth: 3.0
  source_spacing: ico-4  # Coarser mesh for improved statistical power

# 5. Statistical Analysis Parameters
stats:
  analysis_window: [0.100, 0.300]
  p_threshold: 0.15
  cluster_alpha: 0.05
  n_permutations: 10000
  tail: 0  # two-sided test
  seed: 42  # for reproducibility
  method: threshold
  tfce:
    start: 0.0
    step: 0.2
  n_jobs: -1
  buffer_size: 1000

  # Vertex-wise clustering ONLY (exploratory spatial mapping)
  vertex:
    enabled: true

  # Label Time-Series Analysis (DISABLED for vertex-only analysis)
  label_timeseries:
    enabled: false
    mode: "only"
    parc: aparc

  # ROI restriction to frontal/ACC (based on sensor Cluster #2)
  roi:
    parc: aparc
    labels:
      - rostralanteriorcingulate
      - caudalanteriorcingulate
      - superiorfrontal
      - rostralmiddlefrontal
