analysis_name: "source_eloreta_corelabel_c13_31_120_280"
report_group: "13_31"
report_order: 2
domain: "source"

epoch_window:
  tmin: -0.2
  tmax: 0.496
  baseline: [-0.2, 0.0]

contrast:
  name: "1↔3 Transition: Increasing vs. Decreasing"
  condition_A:
    name: "1 to 3 (Increasing)"
    condition_set_name: "TRANSITION_13"
  condition_B:
    name: "3 to 1 (Decreasing)"
    condition_set_name: "TRANSITION_31"
  combination_weights: [1, -1]

source:
  method: "eLORETA"
  snr: 2.0
  pick_ori: normal

inverse:
  loose: 0.2
  depth: 0.8
  source_spacing: ico-4

postprocess:
  align_sign: false
  make_magnitude: false
  save_subject_stc: false
  dump_window_average: false
  normalize_log_total_current: false

stats:
  analysis_window: [0.120, 0.280]
  p_threshold: 0.05
  cluster_alpha: 0.05
  n_permutations: 5000
  tail: 0
  seed: 42
  method: threshold
  n_jobs: -1
  buffer_size: 1000

  vertex:
    enabled: false

  label_timeseries:
    enabled: true
    mode: "mean_flip"
    parc: "c13_31"
    restrict_to:
      - c13_31_core-lh
      - c13_31_core-rh

