# configs/13_31/source_dspm_wholebrain_13_31.yaml

# Whole-brain exploratory source analysis
# Tests ALL cortical regions to ensure no major brain areas are overlooked
# Uses label time-series only (vertex-wise would be too slow for whole brain)

# 1. Metadata
analysis_name: "source_dspm_wholebrain_13_31"
domain: "source"

# 2. Epoch Time Window and Baseline Correction
epoch_window:
  tmin: -0.2
  tmax: 0.496
  baseline: [-0.2, 0.0]

# 3. Contrast Definition
# Tests: Full dipole window (96-300 ms) covering both sensor clusters
contrast:
  name: "1↔3 Transition: Increasing vs. Decreasing"
  condition_A:
    name: "1 to 3 (Increasing)"
    condition_set_name: "TRANSITION_13"
  condition_B:
    name: "3 to 1 (Decreasing)"
    condition_set_name: "TRANSITION_31"
  combination_weights: [1, -1]

# 4. Source Reconstruction Parameters
source:
  method: "dSPM"
  snr: 2.0
  pick_ori: vector

# --- Inverse Solution Parameters ---
inverse:
  loose: 0.2
  depth: 3.0
  source_spacing: ico-4

# 5. Statistical Analysis Parameters
stats:
  analysis_window: [0.096, 0.300]  # Full dipole window (Cluster #1 onset to Cluster #2 end)
  p_threshold: 0.15
  cluster_alpha: 0.001  # Conservative: Bonferroni correction for ~34 labels (0.05/34 ≈ 0.0015)
  n_permutations: 10000
  tail: 0  # two-sided test
  seed: 42
  method: threshold
  tfce:
    start: 0.0
    step: 0.2
  n_jobs: -1
  buffer_size: 1000

  # Vertex-wise clustering (OPTIONAL - currently disabled for computational efficiency)
  # Whole-brain vertex-wise analysis would be very slow (~20,484 vertices)
  # vertex:
  #   enabled: false  # Set to true for high spatial precision vertex-wise analysis

  # Label Time-Series Analysis (PRIMARY exploratory analysis)
  # Tests ALL 34 cortical labels from FreeSurfer aparc parcellation
  label_timeseries:
    enabled: true
    mode: "only"  # Only run label TS (vertex-wise too slow for whole-brain)
    parc: aparc
    p_threshold: 0.15
    n_permutations: 10000
    cluster_alpha: 0.001  # Bonferroni-corrected alpha for 34 labels
    tail: 0
    labels:
      # === FRONTAL LOBE (11 labels) ===
      - superiorfrontal          # Superior frontal gyrus
      - rostralmiddlefrontal     # Rostral middle frontal gyrus (DLPFC)
      - caudalmiddlefrontal      # Caudal middle frontal gyrus
      - parsopercularis          # Pars opercularis (Broca's area, part 1)
      - parstriangularis         # Pars triangularis (Broca's area, part 2)
      - parsorbitalis            # Pars orbitalis
      - lateralorbitofrontal     # Lateral orbitofrontal cortex
      - medialorbitofrontal      # Medial orbitofrontal cortex
      - precentral               # Precentral gyrus (primary motor)
      - paracentral              # Paracentral lobule
      - frontalpole              # Frontal pole

      # === CINGULATE CORTEX (4 labels) ===
      - rostralanteriorcingulate # Rostral anterior cingulate (rACC)
      - caudalanteriorcingulate  # Caudal anterior cingulate (dACC)
      - posteriorcingulate       # Posterior cingulate cortex (PCC)
      - isthmuscingulate         # Isthmus of cingulate

      # === TEMPORAL LOBE (8 labels) ===
      - superiortemporal         # Superior temporal gyrus
      - middletemporal           # Middle temporal gyrus
      - inferiortemporal         # Inferior temporal gyrus
      - bankssts                 # Banks of superior temporal sulcus
      - fusiform                 # Fusiform gyrus (ventral visual stream)
      - entorhinal               # Entorhinal cortex (medial temporal)
      - parahippocampal          # Parahippocampal gyrus
      - temporalpole             # Temporal pole

      # === PARIETAL LOBE (5 labels) ===
      - superiorparietal         # Superior parietal lobule
      - inferiorparietal         # Inferior parietal lobule
      - supramarginal            # Supramarginal gyrus
      - postcentral              # Postcentral gyrus (primary somatosensory)
      - precuneus                # Precuneus (medial parietal)

      # === OCCIPITAL LOBE (4 labels) ===
      - lateraloccipital         # Lateral occipital cortex
      - lingual                  # Lingual gyrus (ventral occipital)
      - cuneus                   # Cuneus (medial dorsal occipital)
      - pericalcarine            # Pericalcarine cortex (primary visual, V1)

      # === INSULA (1 label) ===
      - insula                   # Insular cortex

# Note: This config tests 34 labels total
# With Bonferroni correction: alpha = 0.05/34 = 0.00147 (using 0.001 to be conservative)
# Any label showing p < 0.001 (cluster-corrected) is considered significant
# This is an EXPLORATORY analysis to ensure no major brain regions were missed
