# configs/13_31/source_dspm_100-300_13_31.yaml

# 1. Metadata
analysis_name: "source_dspm_100-300_13_31"
domain: "source"

# 2. Epoch Time Window and Baseline Correction
epoch_window:
  tmin: -0.2
  tmax: 0.496
  baseline: [-0.2, 0.0]

# 3. Contrast Definition
# Tests: Combined frontal/posterior response for 1<->3 transition (100-300 ms)
contrast:
  name: "1<->3 Transition: Increasing vs. Decreasing"
  condition_A:
    name: "1 to 3 (Increasing)"
    condition_set_name: "TRANSITION_13"
  condition_B:
    name: "3 to 1 (Decreasing)"
    condition_set_name: "TRANSITION_31"
  combination_weights: [1, -1]

# 4. Source Reconstruction Parameters
source:
  method: "dSPM"
  snr: 2.0
  pick_ori: vector

# --- Inverse Solution Parameters ---
inverse:
  loose: 0.2
  depth: 3.0
  source_spacing: ico-4

# 5. Statistical Analysis Parameters
stats:
  analysis_window: [0.100, 0.300]
  p_threshold: 0.15
  cluster_alpha: 0.05
  n_permutations: 10000
  tail: 0  # two-sided test
  seed: 42  # for reproducibility
  method: threshold
  tfce:
    start: 0.0
    step: 0.2
  n_jobs: -1
  buffer_size: 1000
  # Vertex-wise clustering (disabled for label-only analysis)
  # vertex:
  #   enabled: false

  # Label Time-Series Analysis (PRIMARY - frontal/ACC hypothesis testing)
  label_timeseries:
    enabled: true
    mode: "only"
    parc: aparc
    p_threshold: 0.15
    n_permutations: 10000
    cluster_alpha: 0.05
    tail: 0
    labels:
      - rostralanteriorcingulate
      - caudalanteriorcingulate
      - superiorfrontal
      - rostralmiddlefrontal

  roi:
    parc: aparc
    labels:
      - rostralanteriorcingulate
      - caudalanteriorcingulate
      - superiorfrontal
      - rostralmiddlefrontal
