# Project-wide defaults for EEG pipeline

data:
  # Combined preprocessed data is the standard; specify preprocessing variant only
  preprocessing: "hpf_1.5_lpf_35_baseline-on"

epoch_defaults:
  baseline: [-0.2, 0.0]

montage: "GSN-HydroCel-129"
reference: "average"

