# Project-wide defaults for EEG pipeline

data:
  source: "new"                 # 'new' (combined), 'old' (split), or custom path
  preprocessing: "hpf_1.0_lpf_35_baseline-on"

epoch_defaults:
  baseline: [-0.2, 0.0]

montage: "GSN-HydroCel-129"
reference: "average"

