# configs/sensor_prime23-land56_vs_prime56-land23.yaml

# 1. General Analysis Information
analysis_name: "sensor_prime23-land56_vs_prime56-land23"
domain: "sensor"

# 2. Epoch Time Window and Baseline Correction
tmin: -0.1
tmax: 0.6
baseline: [-0.1, 0.0]

# 3. Contrast Definition
contrast:
  name: "Prime(2 or 3) Landing(5 or 6) vs Prime(5 or 6) Landing(2 or 3)"
  condition_A:
    name: "Prime 2/3, Land 5/6"
    condition_set_name: "PRIME_23_LAND_56"
  condition_B:
    name: "Prime 5/6, Land 2/3"
    condition_set_name: "PRIME_56_LAND_23"
  combination_weights: [1, -1]

# 4. Statistical Analysis Parameters
stats:
  p_threshold: 0.001
  cluster_alpha: 0.05
  n_permutations: 1024
  tail: 0  # two-sided test
  seed: 42 # for reproducibility
  connectivity:
    method: "distance"
    threshold: 0.04 # 4 cm

# 5. Visualization Parameters
visualizations:
  erp:
    channels: [] # If empty, will use channels from the most significant cluster
  topomap:
    times: [] # If empty, will use time window from the most significant cluster


