# configs/sensor_prime3-land1_vs_prime1-land3.yaml
#
# Configuration for a sensor-space analysis comparing two specific trial types:
#   - Condition A: Priming on digit 1, landing on digit 3 (code '13')
#   - Condition B: Priming on digit 3, landing on digit 1 (code '31')
#

# 1. General Analysis Information
analysis_name: "sensor_prime1-land3_vs_prime3-land1"
domain: "sensor"

# 2. Epoch Time Window and Baseline Correction
tmin: -0.1
tmax: 0.6
baseline: [-0.1, 0.0]

# 3. Contrast Definition
contrast:
  name: "Prime 1/Land 3 vs. Prime 3/Land 1"
  condition_A:
    name: "Prime 1, Land 3"
    condition_set_name: "PRIME_1_LAND_3"
  condition_B:
    name: "Prime 3, Land 1"
    condition_set_name: "PRIME_3_LAND_1"
  combination_weights: [1, -1]

# 4. Statistical Analysis Parameters
stats:
  p_threshold: 0.001
  cluster_alpha: 0.05
  n_permutations: 1024
  tail: 0  # two-sided test
  seed: 42 # for reproducibility
  connectivity:
    method: "distance"
    threshold: 0.04 # 4 cm

# 5. Visualization Parameters
visualizations:
  erp:
    channels: [] # If empty, will use channels from the most significant cluster
  topomap:
    times: [] # If empty, will use time window from the most significant cluster
