# SFN2/configs/source_landing1_all_vs_landing3_all.yaml

# 1. General Analysis Information
analysis_name: "source_landing1_all_vs_landing3_all"
domain: "source"

# 2. Epoch Time Window and Baseline Correction
# Target sensor Cluster #1 window (96–300 ms)
tmin: 0.12
tmax: 0.16
baseline: [-0.1, 0.0]

# 3. Contrast Definition
contrast:
  name: "All Landing on 1 vs All Landing on 3"
  condition_A:
    name: "Landing on 1 (all primes)"
    condition_set_name: "LANDING_ON_1_ALL"
  condition_B:
    name: "Landing on 3 (all primes)"
    condition_set_name: "LANDING_ON_3_ALL"
  combination_weights: [1, -1]

# 4. Source Reconstruction Parameters
source:
  method: "dSPM"
  snr: 2.0

# 5. Statistical Analysis Parameters
stats:
  p_threshold: 0.05
  cluster_alpha: 0.05
  n_permutations: 10000
  tail: 1
  seed: 42
  method: threshold
  n_jobs: 6
  buffer_size: 1000
  roi:
    parc: aparc
    labels:
      - cuneus
      - lingual
      - lateraloccipital
  label_timeseries:
    parc: aparc
    labels:
      - cuneus
      - lingual


