# configs/source_prime1-land4_vs_prime4-land1.yaml

# 1. General Analysis Information
analysis_name: "source_prime1-land4_vs_prime4-land1"
domain: "source"

# 2. Epoch Time Window and Baseline Correction
# WIDENED to better capture the full N1 effect
tmin: 0.100
tmax: 0.200
baseline: [-0.1, 0.0]

# 3. Contrast Definition
contrast:
  name: "Prime 1/Land 4 vs. Prime 4/Land 1"
  condition_A:
    name: "Prime 1, Land 4"
    condition_set_name: "PRIME_1_LAND_4"
  condition_B:
    name: "Prime 4, Land 1"
    condition_set_name: "PRIME_4_LAND_1"
  combination_weights: [1, -1]

# 4. Source Reconstruction Parameters
source:
  method: "dSPM"
  snr: 2.0

# --- Inverse Solution Parameters ---
# These are excellent EEG-appropriate defaults.
inverse:
  loose: 0.2
  depth: 3.0

# 5. Statistical Analysis Parameters
stats:
  p_threshold: 0.01  # RELAXED for more sensitivity
  cluster_alpha: 0.05
  n_permutations: 5000 # INCREASED for publication quality
  tail: 0 # Let's stick to a two-tailed test unless you have a very strong directional hypothesis
  seed: 42
  method: threshold
  n_jobs: 6
  buffer_size: 1000
  # KEEPING the excellent ROI restriction
  roi:
    parc: aparc
    labels:
      - cuneus
      - lingual
      - lateraloccipital