# configs/source_prime23-land56_vs_prime56-land23.yaml

# 1. General Analysis Information
analysis_name: "source_prime23-land56_vs_prime56-land23"
domain: "source"

# 2. Epoch Time Window and Baseline Correction
# Start broad; we can narrow if needed based on sensor results
tmin: 0.08
tmax: 0.20
baseline: [-0.1, 0.0]

# 3. Contrast Definition
contrast:
  name: "Prime(2 or 3) Landing(5 or 6) vs Prime(5 or 6) Landing(2 or 3)"
  condition_A:
    name: "Prime 2/3, Land 5/6"
    condition_set_name: "PRIME_23_LAND_56"
  condition_B:
    name: "Prime 5/6, Land 2/3"
    condition_set_name: "PRIME_56_LAND_23"
  combination_weights: [1, -1]

# 4. Source Reconstruction Parameters
source:
  method: "dSPM"
  snr: 2.0

# --- Inverse Solution Parameters ---
# loose: Orientation constraint (0.2 is a good default for EEG)
# depth: Depth weighting. 0.8 is for MEG; ~3.0 is better for EEG.
inverse:
  loose: 0.2
  depth: 3.0

# 5. Statistical Analysis Parameters
stats:
  p_threshold: 0.1
  cluster_alpha: 0.1
  n_permutations: 10000
  tail: 1
  seed: 42
  method: threshold
  n_jobs: 6
  buffer_size: 1000
  roi:
    parc: aparc
    labels:
      # --- Original Visual ROIs ---
      - cuneus
      - lingual
      - lateraloccipital
      # --- Expanded Parietal ROIs (Core Number Network) ---
      - superiorparietal      # Includes the SPL and parts of the IPS
      - inferiorparietal      # Includes the Angular Gyrus
      - precuneus
      - supramarginal         # Often co-activated with parietal regions
      # --- Expanded Prefrontal ROIs (Cognitive Control) ---
      - inferiorfrontal       # MNE label for the gyrus (IFG)
      - middlefrontal         # A common way to target the DLPFC


