# configs/source_prime1-land3_vs_prime3-land1.yaml
#
# Configuration for a source-space analysis comparing two specific trial types:
#   - Condition A: Priming on digit 1, landing on digit 3 (code '13')
#   - Condition B: Priming on digit 3, landing on digit 1 (code '31')
#

# 1. General Analysis Information
analysis_name: "source_prime1-land3_vs_prime3-land1"
domain: "source"

# 2. Epoch Time Window and Baseline Correction
# Focus around the detected peak for brief temporal clustering
tmin: 0.125
tmax: 0.145
baseline: [-0.1, 0.0]

# 3. Contrast Definition
contrast:
  name: "Prime 1/Land 3 vs. Prime 3/Land 1"
  condition_A:
    name: "Prime 1, Land 3"
    condition_set_name: "PRIME_1_LAND_3"
  condition_B:
    name: "Prime 3, Land 1"
    condition_set_name: "PRIME_3_LAND_1"
  combination_weights: [1, -1]

# 4. Source Reconstruction Parameters
source:
  method: "dSPM"
  snr: 2.0

# 5. Statistical Analysis Parameters
stats:
  p_threshold: 0.02
  cluster_alpha: 0.05
  n_permutations: 10000
  tail: 1 # one-sided (positive) test based on ROI sign check
  seed: 42 # for reproducibility
  method: threshold
  n_jobs: 6
  buffer_size: 1000
  roi:
    parc: aparc
    labels:
      - cuneus
  label_timeseries:
    parc: aparc
    labels:
      - pericalcarine
      - cuneus
      - lateraloccipital
      - lingual
