# configs/sensor_no_cross_increasing_vs_decreasing.yaml

# 1. General Analysis Information
analysis_name: "sensor_no_cross_increasing_vs_decreasing"
domain: "sensor"

# 2. Epoch Time Window and Baseline Correction
epoch_window:
  tmin: -0.1
  tmax: 0.6
  baseline: [-0.1, 0.0]

# 3. Contrast Definition
contrast:
  name: "No Cross Increasing vs. Decreasing"
  condition_A:
    name: "No Cross Increasing"
    condition_set_name: "NO_CROSS_INCREASING"
  condition_B:
    name: "No Cross Decreasing"
    condition_set_name: "NO_CROSS_DECREASING"
  combination_weights: [1, -1]

# 4. Statistical Analysis Parameters
stats:
  analysis_window: [0.07, 0.6]
  p_threshold: 0.005
  cluster_alpha: 0.01
  n_permutations: 1024
  tail: 0  # two-sided test
  seed: 42 # for reproducibility
  connectivity:
    method: "distance"
    threshold: 0.04 # 4 cm

# 5. Visualization Parameters
visualizations:
  erp:
    channels: []
  topomap:
    times: []
