# configs/source_dspm_no_cross_increasing_vs_decreasing.yaml

# 1. General Analysis Information
analysis_name: "source_dspm_no_cross_increasing_vs_decreasing"
domain: "source"

# 2. Epoch Time Window and Baseline Correction
epoch_window:
  tmin: -0.1
  tmax: 0.6
  baseline: [-0.1, 0.0]

# 3. Contrast Definition
contrast:
  name: "No Cross Increasing vs. Decreasing"
  condition_A:
    name: "No Cross Increasing"
    condition_set_name: "NO_CROSS_INCREASING"
  condition_B:
    name: "No Cross Decreasing"
    condition_set_name: "NO_CROSS_DECREASING"
  combination_weights: [1, -1]

# 4. Source Reconstruction Parameters
source:
  method: "dSPM"
  snr: 2.0

# --- Inverse Solution Parameters ---
inverse:
  loose: 0.2
  depth: 3.0

# 5. Statistical Analysis Parameters
stats:
  analysis_window: [0.1, 0.18]
  p_threshold: 0.05
  cluster_alpha: 0.05
  n_permutations: 10000
  tail: 0 # two-sided test initially
  seed: 42 # for reproducibility
  method: threshold
  n_jobs: -1
  buffer_size: 1000
  # ADDED: ROI restriction to increase statistical power
  roi:
    parc: aparc
    labels:
      - lateraloccipital
      - fusiform
      - cuneus
      - lingual
      - inferiorparietal
      - superiorparietal
