# GitHub Pages Configuration
# Simple static site - no Jekyll processing needed

# Site settings
title: EEG Source Localization Pipeline
description: Reproducible sensor-space and source-space EEG analysis pipeline
author: Language and Cognitive Neuroscience Lab

# Build settings
theme: null
plugins: []

# Exclude from processing
exclude:
  - README.md
  - LICENSE

# Include everything else
include:
  - _config.yml
