analysis_name: "sensor_movie_11_21"
report_group: "movie_11_21"
domain: "sensor"

contrast:
  name: "Movie: 11 vs 21"
  condition_A:
    name: "Cardinality 1 (11)"
    conditions: ["11"]
    accuracy: all
  condition_B:
    name: "2 to 1 (21)"
    conditions: ["21"]
    accuracy: acc1
  combination_weights: [1, -1]

