analysis_name: "sensor_movie_32_64"
report_group: "movie_32_64"
domain: "sensor"

contrast:
  name: "Movie: 32 vs 64"
  condition_A:
    name: "3 to 2"
    conditions: ["32"]
    accuracy: acc1
  condition_B:
    name: "6 to 4"
    conditions: ["64"]
    accuracy: acc1
  combination_weights: [1, -1]

