analysis_name: "sensor_movie_21_31"
report_group: "movie_21_31"
domain: "sensor"

contrast:
  name: "Movie: 21 vs 31"
  condition_A:
    name: "2 to 1 (21)"
    conditions: ["21"]
    accuracy: acc1
  condition_B:
    name: "3 to 1 (31)"
    conditions: ["31"]
    accuracy: acc1
  combination_weights: [1, -1]

