analysis_name: "sensor_movie_11_31"
report_group: "movie_11_31"
domain: "sensor"

contrast:
  name: "Movie: 11 vs 31"
  condition_A:
    name: "Cardinality 1 (11)"
    conditions: ["11"]
    accuracy: all
  condition_B:
    name: "3 to 1 (31)"
    conditions: ["31"]
    accuracy: acc1
  combination_weights: [1, -1]

