analysis_name: "sensor_movie_cardinality1_vs_cardinality3"
report_group: "movie_cardinality1_vs_cardinality3"
domain: "sensor"

epoch_window:
  tmin: -0.2
  tmax: 0.496
  baseline: [-0.2, 0.0]

contrast:
  name: "Movie: Card1 vs Card3"
  condition_A:
    name: "Cardinality 1"
    conditions: ["11"]
    accuracy: all
  condition_B:
    name: "Cardinality 3"
    conditions: ["33"]
    accuracy: all
  combination_weights: [1, -1]

