analysis_name: "sensor_movie_11_31"
report_group: "movie_11_31"
domain: "sensor"

epoch_window:
  tmin: -0.2
  tmax: 0.496
  baseline: [-0.2, 0.0]

contrast:
  name: "Movie: 11 vs 31"
  condition_A:
    name: "Cardinality 1 (11)"
    condition_set_name: "CARDINALITY_1"
  condition_B:
    name: "3 to 1 (31)"
    condition_set_name: "TRANSITION_31"
  combination_weights: [1, -1]

