analysis_name: "sensor_movie_13_31"
report_group: "movie_13_31"
domain: "sensor"

contrast:
  name: "Movie: 13 vs 31"
  condition_A:
    name: "1 to 3 (Increasing)"
    conditions: ["13"]
    accuracy: acc1
  condition_B:
    name: "3 to 1 (Decreasing)"
    conditions: ["31"]
    accuracy: acc1
  combination_weights: [1, -1]

