analysis_name: "sensor_movie_cardinality1_vs_cardinality3"
report_group: "movie_cardinality1_vs_cardinality3"
domain: "sensor"

contrast:
  name: "Movie: Cardinality 1 vs Cardinality 3"
  condition_A:
    name: "Cardinality 1"
    conditions: ["11"]
    accuracy: all
  condition_B:
    name: "Cardinality 3"
    conditions: ["33"]
    accuracy: all
  combination_weights: [1, -1]

