analysis_name: "sensor_movie_23_46"
report_group: "movie_23_46"
domain: "sensor"

contrast:
  name: "Movie: 23 vs 46"
  condition_A:
    name: "2 to 3"
    conditions: ["23"]
    accuracy: acc1
  condition_B:
    name: "4 to 6"
    conditions: ["46"]
    accuracy: acc1
  combination_weights: [1, -1]

