analysis_name: "sensor_movie_13_31"
report_group: "movie_13_31"
domain: "sensor"

epoch_window:
  tmin: -0.2
  tmax: 0.496
  baseline: [-0.2, 0.0]

contrast:
  name: "Movie: 13 vs 31"
  condition_A:
    name: "1 to 3 (Increasing)"
    condition_set_name: "TRANSITION_13"
  condition_B:
    name: "3 to 1 (Decreasing)"
    condition_set_name: "TRANSITION_31"
  combination_weights: [1, -1]

