# configs/sensor_cardinality1_vs_cardinality3.yaml

# 1. General Analysis Information
analysis_name: "sensor_cardinality1_vs_cardinality3"
domain: "sensor"

# 2. Epoch Time Window and Baseline Correction
epoch_window:
  tmin: -0.1
  tmax: 0.6
  baseline: [-0.1, 0.0]

# 3. Contrast Definition
contrast:
  name: "Cardinality 1 vs. Cardinality 3"
  condition_A:
    name: "Cardinality 1"
    condition_set_name: "CARDINALITY_1"
  condition_B:
    name: "Cardinality 3"
    condition_set_name: "CARDINALITY_3"
  combination_weights: [1, -1]

# 4. Statistical Analysis Parameters
stats:
  analysis_window: [0.00, 0.6]
  p_threshold: 0.01
  cluster_alpha: 0.01
  n_permutations: 1024
  tail: 1  # two-sided test
  seed: 42 # for reproducibility
  connectivity:
    method: "distance"
    threshold: 0.04 # 4 cm
  # --- Optional ROI restriction (sensor space, uncomment to enable) ---
  # Restricts cluster-based permutation testing to specified sensor regions.
  # ROI definitions are centrally managed in configs/sensor_roi_definitions.yaml
  # roi:
  #   channel_groups:
  #     - posterior_visual_parietal  # Combined N1 + P1 + P3b regions
  # Or specify individual regions:
  # roi:
  #   channel_groups:
  #     - N1_bilateral
  #     - P1_Oz
  #     - P3b_midline

# 5. Visualization Parameters
visualizations:
  erp:
    channels: []
  topomap:
    times: []
