# configs/all_direction_effect/source_loreta_p3b_all_direction_effect.yaml

# 1. General Analysis Information
analysis_name: "source_loreta_p3b_all_direction_effect"
domain: "source"

# 2. Epoch Time Window and Baseline Correction
epoch_window:
  tmin: -0.2
  tmax: 0.496
  baseline: [-0.2, 0.0]

# 3. Contrast Definition
# PRIMARY direction contrast (P3b window)
contrast:
  name: "All Increasing vs. All Decreasing (Full 1-6 Range)"
  condition_A:
    name: "All Increasing Changes"
    condition_set_name: "INCREASING_ALL_CHANGES"
  condition_B:
    name: "All Decreasing Changes"
    condition_set_name: "DECREASING_ALL_CHANGES"
  combination_weights: [1, -1]

# 4. Source Reconstruction Parameters
source:
  method: "eLORETA"
  snr: 2.0

# --- Inverse Solution Parameters ---
inverse:
  loose: 0.2
  depth: 3.0

# 5. Statistical Analysis Parameters
stats:
  analysis_window: [0.30, 0.496]
  # p_threshold is ignored when using TFCE; retained here for reference only.
  p_threshold: 0.1
  cluster_alpha: 0.05
  n_permutations: 10000
  tail: 0 # two-sided test
  seed: 42 # for reproducibility
  method: threshold
  tfce:
    start: 0.0
    step: 0.2
  n_jobs: -1
  buffer_size: 1000
  roi:
    parc: aparc
    labels:
      # P3b canonical generators (parietal/cingulate, NOT visual)
      - inferiorparietal      # Inferior parietal lobule (IPL) - CRITICAL
      - superiorparietal      # Superior parietal lobule (SPL) - CRITICAL
      - precuneus             # Medial parietal - CRITICAL
      - supramarginal         # Angular gyrus, TPJ region - IMPORTANT
      - posteriorcingulate    # Posterior cingulate cortex (PCC)
      - isthmuscingulate      # Isthmus of cingulate
      - superiortemporal      # Superior temporal (TPJ, memory network)
