# configs/source_dspm_all_direction_effect.yaml

# 1. General Analysis Information
analysis_name: "source_dspm_all_direction_effect"
domain: "source"

# 2. Epoch Time Window and Baseline Correction
epoch_window:
  tmin: -0.2
  tmax: 0.496
  baseline: [-0.2, 0.0]

# 3. Contrast Definition
# PRIMARY direction contrast - tests abstract claim with full statistical power
contrast:
  name: "All Increasing vs. All Decreasing (Full 1-6 Range)"
  condition_A:
    name: "All Increasing Changes"
    condition_set_name: "INCREASING_ALL_CHANGES"
  condition_B:
    name: "All Decreasing Changes"
    condition_set_name: "DECREASING_ALL_CHANGES"
  combination_weights: [1, -1]

# 4. Source Reconstruction Parameters
source:
  method: "dSPM"
  snr: 2.0

# --- Inverse Solution Parameters ---
# loose: Orientation constraint (0.2 is a good default for EEG)
# depth: Depth weighting. 0.8 is for MEG; ~3.0 is better for EEG.
inverse:
  loose: 0.2
  depth: 3.0

# 5. Statistical Analysis Parameters
stats:
  analysis_window: [0.00, 0.496]
  p_threshold: 0.05
  cluster_alpha: 0.05
  n_permutations: 10000
  tail: 0 # two-sided test
  seed: 42 # for reproducibility
  method: threshold
  n_jobs: -1
  buffer_size: 1000
  roi:
    parc: aparc
    labels:
      # Key ROIs from Hyde & Spelke (2012) N1 localization
      - lateraloccipital  # For their "extrastriate visual regions"
      - fusiform          # Also mentioned in their "extrastriate" cluster
      - inferiorparietal
      - superiorparietal  # To cover the intraparietal sulcus
      - precuneus
